apiVersion: v1
kind: Service
metadata:
  name: sia-playbook-ppe-service
  labels:
    run: sia-playbook-ppe
spec:
  ports:
  - port: 80
    name: http
  selector:
    run: sia-playbook-ppe
    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sia-playbook-ppe 
spec:
  selector:
    matchLabels:
      run: sia-playbook-ppe
  replicas: 1
  template:
    metadata:
      labels:
        run: sia-playbook-ppe
    spec:
      containers:
          - name: sia-playbook-ppe
            image: siacontainerregistry.azurecr.io/azure/sia-playbook-ppe:latest
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: PPE
            ports:
              - containerPort: 80

